version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: launchpad_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - launchpad_network

  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile.dev
    container_name: launchpad_strapi
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi_password
      DATABASE_SSL: false
      JWT_SECRET: your-jwt-secret-here
      ADMIN_JWT_SECRET: your-admin-jwt-secret-here
      APP_KEYS: your-app-keys-here
      API_TOKEN_SALT: your-api-token-salt-here
      TRANSFER_TOKEN_SALT: your-transfer-token-salt-here
      NODE_ENV: development
    volumes:
      - ./strapi:/srv/app
      - /srv/app/node_modules
      - /srv/app/.tmp
    depends_on:
      - postgres
    networks:
      - launchpad_network

volumes:
  postgres_data:

networks:
  launchpad_network:
    driver: bridge
