name: Deploy All (Strapi + Next.js)

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'package.json'
      - 'README.md'
      - 'scripts/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy-all.yml'

jobs:
  deploy-strapi:
    runs-on: ubuntu-latest
    name: Deploy Strapi to VPS
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          cd ${{ secrets.PROJECT_PATH || '/opt/alejandro-louro' }}
          
          # Determine branch and environment
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            BRANCH="main"
            ENV="production"
            ENV_FILE="env.production"
            DEPLOY_SCRIPT="./scripts/deploy-stack-prod.sh"
            STACK_NAME="alejandro-louro-prod"
            HEALTH_PORT="1337"
          else
            BRANCH="dev"
            ENV="development"
            ENV_FILE="env.dev"
            DEPLOY_SCRIPT="./scripts/deploy-stack-simple.sh"
            STACK_NAME="alejandro-louro-dev"
            HEALTH_PORT="1339"
          fi
          
          echo "🚀 Deploying to $ENV environment..."
          
          git pull origin $BRANCH
          
          # Make scripts executable
          chmod +x scripts/*.sh
          
          # Check if environment file exists
          if [ ! -f $ENV_FILE ]; then
            echo "❌ Error: $ENV_FILE not found!"
            echo "Creating from template..."
            cp env.example $ENV_FILE
            echo "⚠️  Please configure your $ENV_FILE with proper values!"
            exit 1
          fi
          
          # Deploy using the appropriate script
          echo "📦 Running deployment script: $DEPLOY_SCRIPT"
          $DEPLOY_SCRIPT
          
          # Wait for services to be ready
          echo "⏳ Waiting for services to be ready..."
          sleep 30
          
          # Check if Strapi is running
          HEALTH_URL="http://localhost:$HEALTH_PORT/health"
          
          if curl -f $HEALTH_URL > /dev/null 2>&1; then
            echo "✅ Strapi deployment successful for $ENV environment!"
          else
            echo "❌ Strapi health check failed"
            echo "📋 Checking service logs..."
            docker service logs ${STACK_NAME}_strapi --tail=20
            exit 1
          fi
          
          # Show final status
          echo "📊 Final stack status:"
          docker stack services $STACK_NAME
          
          # Clean up unused images
          docker image prune -f

  deploy-nextjs:
    runs-on: ubuntu-latest
    name: Deploy Next.js to Vercel
    needs: deploy-strapi
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        cache-dependency-path: next/yarn.lock

    - name: Install dependencies
      working-directory: ./next
      run: yarn install --frozen-lockfile

    - name: Build Next.js app
      working-directory: ./next
      run: yarn build
      env:
        NEXT_PUBLIC_STRAPI_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_URL }}

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./next
        vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '--preview' }}

  notify:
    runs-on: ubuntu-latest
    needs: [deploy-strapi, deploy-nextjs]
    if: always()
    
    steps:
    - name: Notify deployment status
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ needs.deploy-strapi.result == 'success' && needs.deploy-nextjs.result == 'success' && 'success' || 'failure' }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        text: |
          🚀 Full deployment completed!
          - Environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
          - Strapi: ${{ needs.deploy-strapi.result }}
          - Next.js: ${{ needs.deploy-nextjs.result }}
          - Branch: ${{ github.ref_name }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 